### ISSUE TITLE
Eagle errors!

### ISSUE THREAD

**Issue by T-Skov** [OLIMEX/PIC32-HMZ144#1]
I have a little experience with Kicad, but none with Eagle, ver. 9.5.2.free, but  46 errors?

<img width="396" alt="hmz-144" src="https://user-images.githubusercontent.com/43986842/97561332-4cfdc400-19e0-11eb-9c9e-ba55f4ded17e.png">

**Comment by DanKoloff** [comment]
This is not an issue. Also this is a text we have placed. It is not generated from the Eagle. 46 DRC check errors (44 top layer and 2 bottom layer) are expected and manually confirmed to NOT be actual errors. We place this list in case you receive more or less when you run DRC. This means your DRC rules are not properly set.

These are limitations of the Eagle software version 4.16r2 that we used for design back then. Nothing can be done better. 

Eagle software version 4.16r2 has global design rules for the board design - and the DRC clearance for the main processor and the rest of the board is different! You can lower the value of the clearance check to less and there would be less errors - however this is a recommended clearance only around the main processor - for the rest of the board the engineers here try to use no less than 5.0 mils between wires (and thus clearance) in order to avoid PCB manufacturing problems! So yes lower the clearance and there would be less errors, but the check might lose consistency and validity and ultimately - its purpose.
